### ISSUE TITLE
Inference not proper when deploying with this pipeline

### ISSUE THREAD

**Issue by Windson9** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#18]
Hello, 

I have trained the detectnetV2 model on custom dataset using TAO toolkit. However, when I deploy the model with Isaac ROS Gems pipeline, the output inference is not reflecting the output metrics and the inference that I am seeing while using the TAO pipeline. 

Later, I deployed the same model with deepstream and noticed that inference was as per the output metrics which I noticed while training the model. 

I tried matching the hyper-parameters in the _params.yaml_ file to match the config file of deepstream which I had used but there was no significant improvement in output inference. I am attaching the output images for i) TAO inference ii) Isaac ROS Gems inference iii) Deepstream inference for reference

Model was trained on 6000 images with 500 epochs which gave average precision(mAP) of ~95%. The config file used for training is same provided with DetectnetV2 for TAO training, no changes were done. 

Isaac ROS Gems:
![Screenshot from 2022-12-01 18-37-25](https://user-images.githubusercontent.com/37536581/209664385-c7026823-b027-440a-86c6-664ef91bc114.png)

TAO inference:
![rgb_80](https://user-images.githubusercontent.com/37536581/209664633-339395ba-9bcd-4cf8-b5d3-8464eaf09a80.png)

Deep-stream:
![Screenshot from 2022-12-27 17-41-04](https://user-images.githubusercontent.com/37536581/209664917-37491f37-fbbd-4dff-89c5-b7cddad59081.png)

Thanks,
Mayank

**Comment by hemalshahNV** [comment]
This is likely a parameter tuning mismatch between the defaults for NMS and DBScan in Deepstream/TAO versus `isaac_ros_detectnet`. Could you share the original input image and a sample of your launch graph so we can reproduce exactly what you're seeing?

**Comment by Windson9** [comment]
Sure, I am sharing the input image. I don't know how you reproduce it at your end as for inference. As for launch graph, I understand you mean the launch (parmas) file which contains the hyper-parameters.
Params file (yaml)- 
[params.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/files/10373284/params.txt)

Detectnet_node file (yaml) - 
[detectnet_node.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/files/10373291/detectnet_node.txt)

![rgb_1955](https://user-images.githubusercontent.com/37536581/211312013-c31da1a0-3438-4b42-9211-a6b0f6b628f5.png)

**Comment by HyunCello** [comment]
Hello, I got the same problem when I test custom images even if nothing changed.

![peoplenet_result3](https://user-images.githubusercontent.com/55573388/212286556-0e11c0df-8cb9-42e2-b96e-5c22ff84c5e2.png)
![peoplenet_result5](https://user-images.githubusercontent.com/55573388/212286597-09c5d679-743b-4363-826a-a7a01cfd4231.png)
I used person images in COCO dataset for evaluate model, it seems very different from example.

Is there any resolution problem in models? 
I tried two things, change Input resolution in model and change image resolution but nothing works well.

Also, is there something problem in quantization?

Thank you.

**Comment by gsingh81** [comment]
Hi Hemal and Ashwin,

Mayank has already provided details on detectnet v2 issue. Can you please let us know if were able to check/reproduce it at your side. 
As you mentioned that this is a tuning mismatch between the defaults for NMS and DBScan in Deepstream/TAO versus isaac_ros_detectnet, we are looking forward to a solution. 
just to update, we have already been selected for GTC talk and need your quick support. we are planning to showcase isaac ros gems with AI-ML pipeline on robot. and GTC deadlines are coming closer. 
Looking forward to your feedback

Thanks
Gurpreet

**Comment by hemalshahNV** [comment]
We believe we've traced this to an issue with keeping aspect ratio in DNN Image Encoder that is likely squashing the images being fed in for inference causing some of the odd performance issues here. We'll push out fixes as soon as we can.

**Comment by jaiveersinghNV** [comment]
Thanks for your patience @Windson9 @gsingh81 @HyunCello - we've just merged a [PR](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/pull/27) that includes a fix to the Isaac ROS DNN Image Encoder. 

With the new fix, the encoder should properly preserve the aspect ratio of input images during the resize operation. We suspect that this distortion may have been the root cause of the performance degradation you observed.

Could you please update your checkouts of `isaac_ros_dnn_inference` and let us know if this solves your issue?

**Comment by Windson9** [comment]
Hi @jaiveersinghNV, thanks for the response and quick update.

Unfortunately, the issues still persist on my end. I pulled the latest changes and built the package with the latest changes. There is no improvement in inference at my end.

**Comment by jaiveersinghNV** [comment]
Sorry that this didn't fix it for you - there may be a deeper problem here. We'll look into the Detectnet Decoder component of this pipeline and see if we can identify any discrepancies there.
